name = "Cell_IA"
uuid = "466ded5e-d711-40d1-bdce-35a3fe75cb17"
authors = ["Celia Hermoso Soto <celhersot@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Agents = "46ada45e-f475-11e8-01d0-f70cc89e6671"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Agents = "6.2.10"
CairoMakie = "0.13.10"
FFTW = "1.10.0"
GLMakie = "0.11.11"
LinearAlgebra = "1.11.0"
Makie = "0.22.10"
Random = "1.11.0"
Statistics = "1.11.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
