[model]
g_size = [50, 50]
p_live_agents = 0.30
min_to_live = 2
max_to_live = 3
seed = 125

[video]
filename = "gol.mp4"
title = "Game of Life"
agent_shape = "rect"
agent_size = 13
sim_framerate = 9
sim_frames = 50
color1 = "yellow"
color2 = "green"