[simulation]
model_name = "GameOfLife"
seed = 125
steps = 100                                      # Horizonte temporal (opcional)

[space]
type = "grid"                                    # Opciones: grid, continuous, graph
dimensions = [50, 50]
periodic = true
metric = "chebyshev"                             # Para espacios continuos o grid complejos

[agents]
type = "GridAgent"                               # Definirá qué struct usar
total_count = 0                                  # Si es 0, se usa la densidad
density = 0.3                                    # Porcentaje de ocupación inicial
scheduler = "random"                             # random, by_id, fastest...

[rules]
evolution_rule = "gol_step!"                     # EL NOMBRE DE LA FUNCIÓN en Julia
initialization_rule = "random_placement"

[properties]
# AQUÍ van los parámetros específicos del modelo (GoL, Lenia, Predador, etc)
min_to_live = 2
max_to_live = 3

[visualization]
filename = "simulation.mp4"
title = "Simulación Genérica"
agent_shape = "rect"
agent_size = 13
framerate = 10
frames = 50
color_scheme = { dead = "yellow", alive = "green" } # Mapa de colores
variable_to_color = "state"                     # Qué variable del agente define el color