[simulation]
model_name = "GameOfLife"
seed = 125
steps = 100

[space]
type = "grid"                                    # Options: grid, continuous, graph
dimensions = [50, 50]
periodic = true
metric = "chebyshev"                             # Options: chebyshev, manhattan, euclidean

[agents]
type = "GridAgent"                               # The agent structure by default
total_count = 0                                  # If 0, the density will be used
density = 0.3                                    # Initial ocupation percent
scheduler = "random"                             # Random, by_id, fastest...

[rules]
evolution_rule = "gol_step_asyn!"
initialization_rule = "random_placement"         # Options: random_placement, sorted_placement_h, sorted_placement_v

[properties]
min_to_live = 2
max_to_live = 3

[visualization]
filename = "simulation.mp4"
title = "Simulación Genérica"
agent_shape = "rect"
agent_size = 13
framerate = 10
frames = 50
color_scheme = { dead = "yellow", alive = "green" } # Color map
variable_to_color = "state"