[simulation]
model_name = "GameOfLife"
seed = 125
steps = 100

[space]
type = "grid"                                    # Options: grid, continuous, graph
dimensions = [50, 50]
periodic = true
metric = "chebyshev"                             # Options: chebyshev, manhattan, euclidean

[agents]
n_state = 1
type = "GridAgent"                               # The agent structure by default
total_count = 0                                  # If 0, the density will be used
density = 0.3                                    # Initial ocupation percent
scheduler = "random"                             # Random, by_id, fastest...

[rules]
agent_step = "gol_step_syn!" 
model_step = "gol_model_step!"
initialization_rule = "random_placement"      # Options: random_placement, sorted_placement_h, sorted_placement_v

[properties]
min_to_live = 2
max_to_live = 3

[visualization]
filename = "simulation_syn_sorted_h.mp4"
title = "GoL"
agent_shape = "rect"
agent_size = 13
framerate = 10
frames = 50
color_scheme = { dead = "white", alive = "black" } # Color map
variable_to_color = "state"